FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libc-dev libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY backend/requirements/ /app/requirements/
RUN pip install --no-cache-dir -r requirements/development.txt

COPY backend/ .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
