export const theme = {
  bg: '#e8ecf2',
  bgDark: '#d1d6df',
  cardBg: '#eef2f7',
  primary: '#5b6abf',
  primaryLight: '#7b88d4',
  primaryDark: '#4a58a8',
  accent: '#f97316',
  text: '#2d3436',
  textSecondary: '#636e72',
  textLight: '#b2bec3',
  white: '#ffffff',
  shadowDark: 'rgba(163,177,198,0.5)',
  shadowLight: 'rgba(255,255,255,0.8)',
  radius: 16,
  radiusSm: 10,
}

export const neo = {
  convex: {
    background: theme.cardBg,
    boxShadow: `8px 8px 16px ${theme.shadowDark}, -8px -8px 16px ${theme.shadowLight}`,
    borderRadius: theme.radius,
    border: '1px solid rgba(255,255,255,0.3)',
  },
  concave: {
    background: theme.bg,
    boxShadow: `inset 6px 6px 12px ${theme.shadowDark}, inset -6px -6px 12px ${theme.shadowLight}`,
    borderRadius: theme.radiusSm,
    border: 'none',
  },
  pressed: {
    background: theme.bgDark,
    boxShadow: `inset 4px 4px 8px rgba(163,177,198,0.6), inset -4px -4px 8px rgba(255,255,255,0.6)`,
    borderRadius: theme.radiusSm,
    border: 'none',
  },
  button: {
    background: `linear-gradient(145deg, ${theme.primaryLight}, ${theme.primaryDark})`,
    boxShadow: `5px 5px 12px ${theme.shadowDark}, -5px -5px 12px ${theme.shadowLight}`,
    borderRadius: theme.radiusSm,
    border: 'none',
    color: theme.white,
    fontWeight: 600,
    textTransform: 'none' as const,
    transition: 'all 0.15s ease',
    '&:hover': {
      boxShadow: `3px 3px 8px ${theme.shadowDark}, -3px -3px 8px ${theme.shadowLight}`,
      transform: 'translateY(-1px)',
    },
    '&:active': {
      boxShadow: `inset 4px 4px 8px rgba(74,88,168,0.4), inset -4px -4px 8px rgba(123,136,212,0.4)`,
      transform: 'translateY(0)',
    },
  },
  input: {
    background: theme.bg,
    boxShadow: `inset 4px 4px 8px ${theme.shadowDark}, inset -4px -4px 8px ${theme.shadowLight}`,
    borderRadius: `${theme.radiusSm}px`,
    border: 'none',
    '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '&:hover .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '&.Mui-focused .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '& input': { color: theme.text },
    '& textarea': { color: theme.text },
    '& .MuiInputLabel-root': { color: theme.textSecondary },
    '&.Mui-focused .MuiInputLabel-root': { color: theme.primary },
  },
  select: {
    background: theme.bg,
    boxShadow: `inset 4px 4px 8px ${theme.shadowDark}, inset -4px -4px 8px ${theme.shadowLight}`,
    borderRadius: `${theme.radiusSm}px`,
    border: 'none',
    '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '&:hover .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '&.Mui-focused .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '& .MuiSelect-icon': { color: theme.textSecondary },
    color: theme.text,
  },
  card: {
    background: theme.cardBg,
    boxShadow: `8px 8px 16px ${theme.shadowDark}, -8px -8px 16px ${theme.shadowLight}`,
    borderRadius: theme.radius,
    border: '1px solid rgba(255,255,255,0.3)',
    transition: 'all 0.2s ease',
    '&:hover': {
      boxShadow: `6px 6px 12px ${theme.shadowDark}, -6px -6px 12px ${theme.shadowLight}`,
      transform: 'translateY(-2px)',
    },
  },
  chip: (color: string) => ({
    background: theme.bg,
    boxShadow: `inset 3px 3px 6px ${theme.shadowDark}, inset -3px -3px 6px ${theme.shadowLight}`,
    borderRadius: 8,
    color: color,
    fontWeight: 600,
    border: 'none',
  }),
  page: {
    minHeight: '100vh',
    background: theme.bg,
  },
}
