# Generated by Django 5.2 on 2026-06-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('showroom_manager', 'Showroom Manager'), ('sales_staff', 'Sales Staff'), ('cr_staff', 'CR Staff'), ('inventory_staff', 'Inventory Staff'), ('finance_staff', 'Finance Staff'), ('customer', 'Customer')], default='sales_staff', max_length=20),
        ),
    ]
